stages:
    - install
    - test
    - build
    - deploy  # dummy stage to follow the template guidelines
    - review
    - dast
    - staging
    - canary
    - production
    - incremental rollout 10%
    - incremental rollout 25%
    - incremental rollout 50%
    - incremental rollout 100%
    - performance
    - cleanup
  
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ROLLOUT_RESOURCE_TYPE: deployment
  STAGING_ENABLED: "true"
  POSTGRES_ENABLED: "false"
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: --build-arg=CI_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME

install_dependencies:
  image: node:latest
  stage: install
  script:
  - yarn install --frozen-lockfile
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
    - node_modules/
  only:
    changes:
      - package-lock.json

testing:
  image: node:latest
  stage: test
  script:
  - yarn test
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
