replicaCount: 1

application:
  tier: frontend

service:
  externalPort: 5000
  internalPort: 5000

prometheus:
  metrics: true

postgresql:
  enabled: false

readinessProbe:
  path: "/exploration"

livenessProbe:
  path: "/exploration"

ingress:
  tls:
    secretName: "tls-secret"
    enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"